### ISSUE TITLE
Notifiation Download link is broken

### ISSUE THREAD

**Issue by tsjazil** [amith-vp/ktunotificationapi#1]
Notfication link is broken. That link will not open anything

**Comment by amith-vp** [comment]
![image](https://user-images.githubusercontent.com/66194856/150357336-4cfe3d5a-15fa-40e2-995e-a6290055ac86.png)
Looks fine. Did you get any failed requests?

**Comment by tsjazil** [comment]
I mean the url from response

**Comment by tsjazil** [comment]
![1642693101](https://user-images.githubusercontent.com/45793120/150371109-a874507b-7aec-4e9b-998c-7e01fcb5e5c6.jpg)
## This one

**Comment by tsjazil** [comment]
May be my problem
I couldn't download the file using that link using wget command in linux

**Comment by amith-vp** [comment]
![image](https://user-images.githubusercontent.com/66194856/150374579-1737ed7e-3a23-4f3c-8653-9cfe694295a7.png)
I think the issue is with the space in between the announcement id and filename. 
![image](https://user-images.githubusercontent.com/66194856/150375084-7870344a-2b97-4e63-83b8-d28c58feabbd.png)
File URL contains space and code format that white space. 
Thanks for reporting.

**Comment by tsjazil** [comment]
Yup,My terminal is showing error after '&' symbol

**Comment by amith-vp** [comment]
I am planning to change the module for scraping. Instead of scraping raw HTML , String would resolve the problems.
thanks for reporting.
